/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0W13RkH
 */
import { Icons } from '@/components/icons';

export function Features() {
  return (
    <section className="w-full py-6 md:py-12 lg:py-16 xl:py-24 bg-black">
      <div className="container px-4 md:px-6">
        <div className="grid gap-6 items-center">
          <div className="flex flex-col justify-center space-y-8 text-center">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none bg-clip-text text-white">
                Features
              </h1>
              <p className="max-w-[600px] text-zinc-200 md:text-xl dark:text-zinc-100 mx-auto">
                Get paid for your work. Pay for others work. Own the SQL.
              </p>
            </div>
            <div className="w-full max-w-full space-y-4 mx-auto">
              <div className="grid grid-cols-3 gap-8">
                <div className="flex flex-col items-center space-y-2 border-gray-800 p-4 rounded-lg">
                  <div className="p-2 bg-black bg-opacity-50 rounded-full">
                    <Icons.shield className="h-10 w-10 text-white" />
                  </div>
                  <h2 className="text-xl font-bold text-white">Own Your SQL</h2>
                  <p className="text-zinc-200 dark:text-zinc-100">
                    Write SQL queries in our editor and mint them as NFTs.
                  </p>
                </div>
                <div className="flex flex-col items-center space-y-2 border-gray-800 p-4 rounded-lg">
                  <div className="p-2 bg-black bg-opacity-50 rounded-full">
                    <Icons.dollar className="h-10 w-10 text-white" />
                  </div>
                  <h2 className="text-xl font-bold text-white">
                    Sell Your SQL
                  </h2>
                  <p className="text-zinc-200 dark:text-zinc-100">
                    Sell your SQL NFTs in our marketplace.
                  </p>
                </div>
                <div className="flex flex-col items-center space-y-2 border-gray-800 p-4 rounded-lg">
                  <div className="p-2 bg-black bg-opacity-50 rounded-full">
                    <Icons.search className="h-10 w-10 text-white" />
                  </div>
                  <h2 className="text-xl font-bold text-white">
                    Preview SQL Data
                  </h2>
                  <p className="text-zinc-200 dark:text-zinc-100">
                    See a preview of the SQL NFT query results before you buy.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
