/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nQlIUCX
 */

import { Button } from '@/components/ui/button';
import { LucideDollarSign, PlusCircle } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';

export function Hero() {
  return (
    <section className="w-full pb-8 pt-0 bg-primary">
      <div className="container px-8 md:px-12">
        <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-6 xl:grid-cols-[1fr_600px]">
          <Image
            alt="Hero"
            src="/logo_v3.png"
            className="lg:order-last"
            height={500}
            width={500}
          />
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h1 className="text-3xl text-dark-blue font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                Web3 SQL Marketplace
              </h1>
              <p className="max-w-[600px] text-zinc-500 md:text-xl dark:text-zinc-400">
                Buy, sell, and mint SQL queries as NFTs.
              </p>
              <p className=" text-zinc-500 dark:text-zinc-400 inline-flex items-center">
                Powered by:{' '}
                <Image
                  height={25}
                  width={125}
                  src="/Logo_Black_256.png"
                  alt="Chainbase"
                  className="inline-block"
                />{' '}
              </p>
            </div>
            <div className="flex gap-4">
              <Button asChild className="bg-secondary p-4">
                <Link href="/market">
                  <LucideDollarSign className="mr-2 h-4 w-4" />
                  Market
                </Link>
              </Button>
              <Button asChild className="bg-white text-black p-4">
                <Link href="/mint">
                  <PlusCircle className="mr-2 h-4 w-4" />
                  Mint
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
