/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nQlIUCX
 */

import { buttonVariants } from '@/components/ui/button';
import Link from 'next/link';

export function Hero() {
  return (
    <section className="w-full py-12 lg:py-16 ">
      <div className="container px-4 md:px-6">
        <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
          <img alt="Hero" className="lg:order-last" src="/logo.jpg" />
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                Welcome to our email client
              </h1>
              <p className="max-w-[600px] text-zinc-500 md:text-xl dark:text-zinc-400">
                Manage all your emails in one place. Securely and efficiently.
              </p>
            </div>
            <div className="flex gap-4">
              <Link href="/buy" className={buttonVariants()}>
                Buy
              </Link>
              <Link
                href="/sell"
                className={buttonVariants({ variant: 'outline' })}
              >
                Sell
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
